site_name: FoamPilot Documentation
site_url: https://stevendaix.github.io/foampilot/

repo_url: https://github.com/stevendaix/foampilot
repo_name: FoamPilot

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: fr
          name: Français
          default: false
          build: true
        - locale: zh
          name: 中文
          default: false
          build: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
nav:
  - Home: en/index.md
  - About: en/about.md
  - Installation:
      - OpenFOAM: en/install_openfoam.md
  - Présentation de FOAMPilot: en/presentation.md
  - Guide théorique: en/fluids_theory.md
  - Guide utilisateur: en/user_documentation.md
  - Partie développement:
      - index: en/dev/dev_index.md
      - introduction : en/dev/dev_intro_documentation.md
      - Modules détailés de FoamPilot : en/dev/dev_detailed_documentation.md
      - Gestion des quantités : en/dev/manage_ValueWithUnit.md
  - Partie exemples:
      - index: en/example/presentation_example.md
      - Étude de cas silencieux : en/example/muffler/detailled_example_muffler.md
      - Étude de cas silencieux : en/example/simplecar/detailled_example.md